// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQdXkfPTrQiHKja006OVw2439ZnyHxVXM',
    appId: '1:180301204443:web:d029b9a7e7b6694de275fe',
    messagingSenderId: '180301204443',
    projectId: 'eventopia-76f01',
    authDomain: 'eventopia-76f01.firebaseapp.com',
    storageBucket: 'eventopia-76f01.firebasestorage.app',
    measurementId: 'G-YNXWRS59QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtL4yzWSPSB3nNDXT1nukTPJxk6zwFtuo',
    appId: '1:180301204443:android:3fd6776f8d5cd3b7e275fe',
    messagingSenderId: '180301204443',
    projectId: 'eventopia-76f01',
    storageBucket: 'eventopia-76f01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRTGd9xvDYcyLila7p3rtr7SzmNXI2zhA',
    appId: '1:180301204443:ios:d4071452d324debce275fe',
    messagingSenderId: '180301204443',
    projectId: 'eventopia-76f01',
    storageBucket: 'eventopia-76f01.firebasestorage.app',
    iosBundleId: 'com.example.eventopia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRTGd9xvDYcyLila7p3rtr7SzmNXI2zhA',
    appId: '1:180301204443:ios:d4071452d324debce275fe',
    messagingSenderId: '180301204443',
    projectId: 'eventopia-76f01',
    storageBucket: 'eventopia-76f01.firebasestorage.app',
    iosBundleId: 'com.example.eventopia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQdXkfPTrQiHKja006OVw2439ZnyHxVXM',
    appId: '1:180301204443:web:d9c3f69a136015d0e275fe',
    messagingSenderId: '180301204443',
    projectId: 'eventopia-76f01',
    authDomain: 'eventopia-76f01.firebaseapp.com',
    storageBucket: 'eventopia-76f01.firebasestorage.app',
    measurementId: 'G-XQ281T9P8H',
  );
}
