import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:provider/provider.dart';
import 'package:qr_flutter/qr_flutter.dart';

import '../../auth/app_provider.dart';
import '../../models.dart';
import '../../theme.dart';
import '../../widgets.dart';

class TicketDetailSheet extends StatelessWidget {
  final Booking booking;
  const TicketDetailSheet({required this.booking});

  Future<void> _downloadTicketPdf(BuildContext context) async {
    try {
      final pdf = pw.Document();

      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          build: (pw.Context ctx) {
            return pw.Column(
              children: [
                // Header
                pw.Container(
                  padding: const pw.EdgeInsets.all(20),
                  decoration: pw.BoxDecoration(
                    color: PdfColors.deepPurple50,
                    borderRadius:
                        const pw.BorderRadius.all(pw.Radius.circular(8)),
                  ),
                  child: pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Column(
                        crossAxisAlignment: pw.CrossAxisAlignment.start,
                        children: [
                          pw.Text('EVENTOPIA',
                              style: pw.TextStyle(
                                  fontSize: 22,
                                  fontWeight: pw.FontWeight.bold,
                                  color: PdfColors.deepPurple)),
                          pw.SizedBox(height: 4),
                          pw.Text('E-TICKET',
                              style: pw.TextStyle(
                                  fontSize: 14,
                                  color: PdfColors.deepPurple300)),
                        ],
                      ),
                      pw.Text('CONFIRMED',
                          style: pw.TextStyle(
                              fontSize: 14,
                              fontWeight: pw.FontWeight.bold,
                              color: PdfColors.green)),
                    ],
                  ),
                ),
                pw.SizedBox(height: 24),

                // Event title
                pw.Text(booking.eventTitle,
                    style: pw.TextStyle(
                        fontSize: 20, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 20),

                // Details table
                pw.TableHelper.fromTextArray(
                  context: ctx,
                  border: null,
                  headerStyle: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.white),
                  headerDecoration:
                      const pw.BoxDecoration(color: PdfColors.deepPurple),
                  cellHeight: 30,
                  cellAlignments: {
                    0: pw.Alignment.centerLeft,
                    1: pw.Alignment.centerRight,
                  },
                  data: [
                    ['Detail', 'Info'],
                    ['Ticket Type', booking.category.label],
                    ['Quantity', '${booking.quantity}'],
                    ['Section', booking.category.section],
                    if (booking.discount > 0)
                      ['Discount', '- NPR ${booking.discount.toStringAsFixed(2)}'],
                    ['Total Paid', 'NPR ${booking.total.toStringAsFixed(2)}'],
                    ['Booked On', DateFormat('dd MMM yyyy').format(booking.createdAt)],
                    ['Reference', booking.id.substring(0, 8).toUpperCase()],
                  ],
                ),

                pw.SizedBox(height: 30),

                // QR Code
                pw.Center(
                  child: pw.Column(
                    children: [
                      pw.Text('Scan this QR at entry',
                          style: const pw.TextStyle(
                              fontSize: 12, color: PdfColors.grey600)),
                      pw.SizedBox(height: 10),
                      pw.BarcodeWidget(
                        barcode: pw.Barcode.qrCode(),
                        data: booking.qrData,
                        width: 140,
                        height: 140,
                      ),
                    ],
                  ),
                ),

                pw.Spacer(),

                // Footer
                pw.Divider(color: PdfColors.grey300),
                pw.SizedBox(height: 8),
                pw.Center(
                  child: pw.Text(
                    'Generated by Eventopia on ${DateFormat('MMMM dd, yyyy').format(DateTime.now())}',
                    style: const pw.TextStyle(
                        fontSize: 9, color: PdfColors.grey),
                  ),
                ),
              ],
            );
          },
        ),
      );

      final bytes = await pdf.save();

      await Printing.sharePdf(
        bytes: bytes,
        filename: 'eventopia_ticket_${booking.id.substring(0, 8)}.pdf',
      );
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to generate PDF: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return DraggableScrollableSheet(
      initialChildSize: .85,
      maxChildSize: .95,
      minChildSize: .4,
      builder: (_, sc) => Container(
        decoration: const BoxDecoration(
          color: C.surface,
          borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
        ),
        padding: const EdgeInsets.fromLTRB(24, 16, 24, 32),
        child: ListView(
          controller: sc,
          children: [
            Center(
              child: Container(
                width: 40, height: 4,
                margin: const EdgeInsets.only(bottom: 16),
                decoration: BoxDecoration(
                    color: C.border, borderRadius: BorderRadius.circular(2)),
              ),
            ),
            Text(booking.eventTitle,
                style: const TextStyle(
                    fontSize: 20, fontWeight: FontWeight.w700)),
            const SizedBox(height: 16),

            Center(
              child: Container(
                width: 200,
                height: 200,
                padding: const EdgeInsets.all(14),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(color: C.border),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withOpacity(0.05),
                      blurRadius: 12,
                      offset: const Offset(0, 4),
                    ),
                  ],
                ),
                child: QrImageView(
                  data: booking.qrData,
                  version: QrVersions.auto,
                ),
              ),
            ),

            const SizedBox(height: 24),

            GCard(
              child: Column(
                children: [
                  InfoRow(
                      icon: Icons.confirmation_number_rounded,
                      label: 'Ticket Type',
                      value:
                      '${booking.category.label} × ${booking.quantity}'),
                  InfoRow(
                      icon: Icons.event_seat_rounded,
                      label: 'Section',
                      value: booking.category.section),
                  InfoRow(
                      icon: Icons.payments_rounded,
                      label: 'Total Paid',
                      value: 'NPR ${booking.total.toStringAsFixed(2)}'),
                  InfoRow(
                      icon: Icons.calendar_today_rounded,
                      label: 'Booked On',
                      value: DateFormat('dd MMM y').format(booking.createdAt)),
                  InfoRow(
                      icon: Icons.tag_rounded,
                      label: 'Ref',
                      value: booking.id.substring(0, 8).toUpperCase()),
                ],
              ),
            ),

            const SizedBox(height: 24),

            GBtn(
              label: 'Download Ticket',
              onTap: () => _downloadTicketPdf(context),
              icon: Icons.download_rounded,
              gradient: const LinearGradient(colors: [C.sky, C.indigo]),
            ),

            const SizedBox(height: 16),

            if (booking.status == BookingStatus.cancelled)
              Container(
                width: double.infinity,
                padding: const EdgeInsets.all(14),
                decoration: BoxDecoration(
                  color: C.rose.withOpacity(0.08),
                  borderRadius: BorderRadius.circular(14),
                  border: Border.all(color: C.rose.withOpacity(0.3)),
                ),
                child: const Row(
                  children: [
                    Icon(Icons.info_outline_rounded, color: C.rose),
                    SizedBox(width: 10),
                    Expanded(
                      child: Text(
                        'This booking is cancelled. The refund has been done.',
                        style: TextStyle(
                          color: C.rose,
                          fontWeight: FontWeight.w500,
                          fontSize: 14,
                        ),
                      ),
                    ),
                  ],
                ),
              )
            else
              OutlinedButton.icon(
                onPressed: () {
                  final cancelled = context
                      .read<AppProvider>()
                      .cancelBooking(booking.id);
                  Navigator.pop(context);
                  ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                    content: Text(cancelled
                        ? 'Booking cancelled. The refund has been done.'
                        : 'Cannot cancel — 7-day window has passed.'),
                  ));
                },
                icon: const Icon(Icons.cancel_rounded, color: C.rose),
                label: const Text('Cancel Booking',
                    style: TextStyle(color: C.rose)),
                style: OutlinedButton.styleFrom(
                  side: const BorderSide(color: C.rose),
                  padding: const EdgeInsets.symmetric(vertical: 14),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(14)),
                ),
              ),
          ],
        ),
      ),
    );
  }
}