import json
import os
import re

en_dict = {
  "whatsPoppinAtHelp": "What's Poppin' at HELP?",
  "soldOut": "SOLD OUT",
  "full": "Full",
  "seatsLeft": "{seats} left",
  "fromNpr": "From NPR {price}",
  "admin": "Admin",
  "organizer": "Organizer",
  "attendee": "Attendee",
  "weak": "Weak",
  "fair": "Fair",
  "good": "Good",
  "strong": "Strong",
  "passwordStrength": "Password strength: {label}",
  "pleaseChangeDefaultPassword": "Please change your default password to continue.",
  "eventopia": "Eventopia",
  "welcomeBack": "Welcome Back!",
  "loginToContinue": "Login to continue",
  "emailAddress": "Email Address",
  "emailIsRequired": "Email is required",
  "password": "Password",
  "passwordIsRequired": "Password is required",
  "forgotPassword": "Forgot Password?",
  "logIn": "Log In",
  "dontHaveAccount": "Don't have an account? ",
  "createAccount": "Create Account",
  "joinEventopia": "Join Eventopia",
  "registeringAs": "Registering as: ",
  "fullName": "Full Name",
  "fullNameIsRequired": "Full name is required",
  "nameIsTooShort": "Name is too short",
  "enterValidEmail": "Enter a valid email address",
  "phoneNumber": "Phone Number",
  "phoneNumberIsRequired": "Phone number is required",
  "enterValidPhoneNumber": "Enter a valid phone number",
  "min6Chars": "Minimum 6 characters",
  "confirmPassword": "Confirm Password",
  "pleaseConfirmPassword": "Please confirm your password",
  "passwordsDoNotMatch": "Passwords do not match",
  "alreadyHaveAccount": "Already have an account?  ",
  "signIn": "Sign In",
  "home": "Home",
  "users": "Users",
  "events": "Events",
  "profile": "Profile",
  "eventRequests": "Event Requests",
  "noPendingRequests": "No pending requests",
  "byOrganizer": "By {organizer}",
  "eventRejected": "Event rejected",
  "reject": "Reject",
  "eventApproved": "Event approved",
  "approve": "Approve",
  "noUserLoggedIn": "No user logged in",
  "administrator": "Administrator",
  "organisers": "Organisers",
  "attendees": "Attendees",
  "revenue": "Revenue",
  "nprRevenue": "NPR {revenue}",
  "quickActions": "Quick Actions",
  "addOrganiser": "Add\nOrganiser",
  "eventRequestsQuickAction": "Event\nRequests",
  "reports": "Reports",
  "allEvents": "All Events",
  "seeAll": "See all",
  "auditoriumOccupancy": "Auditorium Occupancy",
  "seatsBooked": "{booked} / {total} seats booked",
  "myProfile": "My Profile",
  "editProfile": "Edit Profile",
  "name": "Name",
  "phone": "Phone",
  "cancel": "Cancel",
  "pleaseFillAllFields": "Please fill all fields",
  "profileUpdatedSuccessfully": "Profile updated successfully",
  "save": "Save",
  "email": "Email",
  "resetPassword": "Reset Password",
  "newPassword": "New Password",
  "passwordChangedSuccessfully": "Password changed successfully",
  "update": "Update",
  "signOut": "Sign Out",
  "eventopiaAnalytics": "Eventopia Analytics",
  "report": "REPORT",
  "eventDetails": "Event Details",
  "nameDetail": "Name: {name}",
  "dateDetail": "Date: {date}",
  "organizerDetail": "Organizer: {organizer}",
  "locationDetail": "Location: {location}",
  "kpi": "Key Performance Indicators",
  "metric": "Metric",
  "value": "Value",
  "totalTicketsSold": "Total Tickets Sold",
  "totalRevenue": "Total Revenue",
  "occupancyRate": "Occupancy Rate",
  "availableSeats": "Available Seats",
  "salesByTicketCategory": "Sales by Ticket Category",
  "category": "Category",
  "ticketsSold": "Tickets Sold",
  "generatedOnBySystem": "Generated on {date} by Eventopia System",
  "failedToGeneratePdf": "Failed to generate PDF: {error}",
  "reportsAndAnalytics": "Reports & Analytics",
  "noEventsToShowAnalytics": "No events available to show analytics.",
  "selectEvent": "Select Event",
  "ofTotal": "of {total} total",
  "occupancy": "Occupancy",
  "available": "Available",
  "sevenDayRevenue": "7-Day Revenue",
  "salesByCategory": "Sales by Category",
  "passwordChangedPleaseLogin": "Password changed successfully. Please login.",
  "changePassword": "Change Password",
  "enterNewPasswordDesc": "Enter a new password below to secure your account.",
  "entryApprovedFor": "Entry approved for \"{title}\"",
  "qrCodeNotFound": "QR code not found or already used.",
  "qrCheckIn": "QR Check-In",
  "scanQrAtGate": "Scan QR at entry gate",
  "manualQrCodeEntry": "Manual QR Code Entry",
  "enterQrCode": "Enter QR Code",
  "validateEntry": "Validate Entry",
  "noEventsAvailable": "No events available",
  "all": "All",
  "deleteUser": "Delete User",
  "areYouSureDeleteUser": "Are you sure you want to delete {name}?",
  "delete": "Delete",
  "editUser": "Edit User",
  "organisation": "Organisation",
  "manageEvent": "Manage Event",
  "changeStatus": "Change Status",
  "deleteEvent": "Delete Event",
  "areYouSureDeleteEvent": "Are you sure you want to delete this event? This action cannot be undone.",
  "saveChanges": "Save Changes",
  "scanAttendeeQr": "Scan Attendee QR",
  "cameraOpensHere": "Camera opens here",
  "mobileScannerPlugin": "(mobile_scanner plugin)",
  "close": "Close",
  "organiserRegistered": "Organiser Registered!",
  "organiserLoginCredentialsAssigned": "Login credentials have been assigned to the organiser. They can use the default password (Org@1234) and change it on first login.",
  "done": "Done",
  "registerNewOrganiser": "Register New Organiser",
  "defaultPasswordAssignedDesc": "A default password (Org@1234) will be assigned and emailed to the organiser. They must change it on first login.",
  "required": "Required",
  "invalidEmail": "Invalid email",
  "organisationNameOptional": "Organisation Name (optional)",
  "registerOrganiser": "Register Organiser",
  "myEvents": "My Events",
  "analytics": "Analytics",
  "organiser": "Organiser",
  "nprParam": "NPR {param}",
  "promoCodes": "Promo Codes",
  "createAction": "+ Create",
  "noEventsYet": "No events yet.",
  "tapCreateToAddFirstEvent": "Tap \"+ Create\" to add your first event.",
  "create": "Create",
  "eventAnalyticsReport": "EVENT ANALYTICS REPORT",
  "nameParam": "Name: {param}",
  "dateParam": "Date: {param}",
  "kpis": "Key Performance Indicators (KPIs)",
  "generatedBySystem": "Generated by Eventopia System",
  "createEventsToSeeAnalytics": "Create events to see analytics.",
  "downloadPdfReport": "Download PDF Report",
  "ofParamTotal": "of {param} total",
  "ticketVerified": "Ticket Verified",
  "scanFailed": "Scan Failed",
  "ok": "OK",
  "scanTicket": "Scan Ticket",
  "requiredField": "Required",
  "eventAddedSuccessfully": "Event has been added successfully!",
  "createNewEvent": "Create New Event",
  "eventPoster": "Event Poster",
  "change": "Change",
  "remove": "Remove",
  "tapToAddEventPoster": "Tap to add event poster",
  "recommendedPosterSize": "Recommended: 1200 × 800 px",
  "eventTitle": "Event Title",
  "description": "Description",
  "location": "Location",
  "date": "Date",
  "start": "Start",
  "end": "End",
  "ticketCategories": "Ticket Categories",
  "priceNpr": "Price (NPR)",
  "capacity": "Capacity",
  "promoCodeOptional": "Promo Code (Optional)",
  "codeExample": "Code (e.g. SAVE20)",
  "discountPercentage": "Discount %",
  "createEvent": "Create Event",
  "minParam": "Min {param}",
  "editEvent": "Edit Event",
  "time": "Time",
  "seats": "Seats",
  "ticketTypes": "Ticket Types",
  "paramOff": "{param}% off",
  "explore": "Explore",
  "tickets": "Tickets",
  "discoverConnectCelebrate": "Discover. Connect. Celebrate.",
  "myBookings": "My Bookings",
  "totalSpent": "Total Spent",
  "nprAmount": "NPR {amount}",
  "upcomingEvents": "Upcoming Events",
  "noUpcomingEvents": "No upcoming events.",
  "bookings": "Bookings",
  "exploreEvents": "Explore Events",
  "searchEvents": "Search events…",
  "noEventsMatchSearch": "No events match your search.",
  "eventUpper": "EVENT",
  "completedUpper": "COMPLETED",
  "upcomingUpper": "UPCOMING",
  "about": "About",
  "availablePromoCodes": "Available Promo Codes",
  "useCodeForDiscount": "Use code {code} for {discount}% off!",
  "remainingCount": "{count} remaining",
  "eventEnded": "Event Ended",
  "bookNow": "Book Now",
  "notAvailable": "Not Available",
  "myTickets": "My Tickets",
  "upcoming": "Upcoming",
  "past": "Past",
  "cancelled": "Cancelled",
  "noTicketsYet": "No tickets yet.",
  "notifications": "Notifications",
  "noNotificationsYet": "No notifications yet",
  "payment": "Payment",
  "otpSentMessage": "OTP has been sent to your registered mobile/email. (Default: 1234)",
  "invalidOtpMessage": "Invalid OTP. Please try again.",
  "orderSummary": "Order Summary",
  "event": "Event",
  "ticket": "Ticket",
  "categoryQuantity": "{category} × {quantity}",
  "subtotal": "Subtotal",
  "promoCode": "Promo: {code}",
  "negativeNprAmount": "- NPR {amount}",
  "totalToPay": "Total to Pay",
  "selectPaymentMethod": "Select Payment Method",
  "card": "Card",
  "esewa": "eSewa",
  "pay": "Pay",
  "enterOtpToConfirm": "Enter OTP to Confirm Payment",
  "otpLabel": "OTP : 1234",
  "verifyAndPay": "Verify & Pay – NPR {amount}",
  "maxSeatsAllowed": "Maximum 10 seats allowed per booking.",
  "chooseTicketCategoryFirst": "Choose Ticket Category First",
  "categoryPrice": "{category} (NPR {price})",
  "selected": "Selected",
  "booked": "Booked",
  "pleaseSelectCategory": "Please select a ticket category to choose seats",
  "stageUpper": "STAGE",
  "controlRoomUpper": "CONTROL ROOM",
  "seatsSelected": "{count} seat(s) selected",
  "continueAction": "Continue",
  "eventopiaUpper": "EVENTOPIA",
  "eTicketUpper": "E-TICKET",
  "confirmedUpper": "CONFIRMED",
  "detail": "Detail",
  "info": "Info",
  "ticketType": "Ticket Type",
  "quantity": "Quantity",
  "section": "Section",
  "discount": "Discount",
  "totalPaid": "Total Paid",
  "bookedOn": "Booked On",
  "reference": "Reference",
  "scanQrAtEntry": "Scan this QR at entry",
  "generatedBy": "Generated by Eventopia on {date}",
  "ticketConfirmed": "Ticket Confirmed!",
  "showQrAtEntry": "Show this QR code at entry",
  "promoApplied": "Code applied! {discount}% discount",
  "invalidPromoCode": "Invalid or expired code",
  "bookingFailed": "Booking failed. Please try again.",
  "selectTicketType": "Select Ticket Type",
  "countLeft": "{count} left",
  "apply": "Apply",
  "discountWithPercent": "Discount ({discount}%)",
  "total": "Total",
  "selectATicketType": "Select a ticket type",
  "proceedToPay": "Proceed to pay",
  "eventSoldOut": "This event is sold out.",
  "onWaitlist": "You're on the waitlist!",
  "joinWaitlistDesc": "Join the waitlist — we'll notify you when tickets become available.",
  "joinWaitlist": "Join Waitlist",
  "quantityMultiplier": "× {quantity}",
  "downloadTicket": "Download Ticket",
  "bookingCancelledRefunded": "This booking is cancelled. The refund has been done.",
  "bookingCancelledRefundedSuccess": "Booking cancelled. The refund has been done.",
  "cannotCancelWindowPassed": "Cannot cancel — 7-day window has passed.",
  "cancelBooking": "Cancel Booking"
}

ne_dict = {
  "whatsPoppinAtHelp": "HELP मा के हुँदैछ?",
  "soldOut": "बिक्री भयो",
  "full": "पूर्ण",
  "seatsLeft": "{seats} बाँकी",
  "fromNpr": "NPR {price} बाट सुरु",
  "admin": "प्रशासक",
  "organizer": "आयोजक",
  "attendee": "सहभागी",
  "weak": "कमजोर",
  "fair": "ठिकै",
  "good": "राम्रो",
  "strong": "बलियो",
  "passwordStrength": "पासवर्डको बल: {label}",
  "pleaseChangeDefaultPassword": "कृपया अगाडि बढ्नको लागि आफ्नो पूर्वनिर्धारित पासवर्ड परिवर्तन गर्नुहोस्।",
  "eventopia": "Eventopia",
  "welcomeBack": "पुनः स्वागत छ!",
  "loginToContinue": "अगाडि बढ्न लगइन गर्नुहोस्",
  "emailAddress": "इमेल ठेगाना",
  "emailIsRequired": "इमेल आवश्यक छ",
  "password": "पासवर्ड",
  "passwordIsRequired": "पासवर्ड आवश्यक छ",
  "forgotPassword": "पासवर्ड भुल्नुभयो?",
  "logIn": "लग इन गर्नुहोस्",
  "dontHaveAccount": "खाता छैन? ",
  "createAccount": "खाता खोल्नुहोस्",
  "joinEventopia": "Eventopia मा सामेल हुनुहोस्",
  "registeringAs": "यस रूपमा दर्ता गर्दै: ",
  "fullName": "पूरा नाम",
  "fullNameIsRequired": "पूरा नाम आवश्यक छ",
  "nameIsTooShort": "नाम धेरै छोटो छ",
  "enterValidEmail": "मान्य इमेल ठेगाना प्रविष्ट गर्नुहोस्",
  "phoneNumber": "फोन नम्बर",
  "phoneNumberIsRequired": "फोन नम्बर आवश्यक छ",
  "enterValidPhoneNumber": "मान्य फोन नम्बर प्रविष्ट गर्नुहोस्",
  "min6Chars": "कम्तिमा ६ वर्णहरू",
  "confirmPassword": "पासवर्ड पुष्टि गर्नुहोस्",
  "pleaseConfirmPassword": "कृपया आफ्नो पासवर्ड पुष्टि गर्नुहोस्",
  "passwordsDoNotMatch": "पासवर्डहरू मेल खाँदैनन्",
  "alreadyHaveAccount": "पहिले नै खाता छ?  ",
  "signIn": "साइन इन गर्नुहोस्",
  "home": "गृह",
  "users": "प्रयोगकर्ताहरू",
  "events": "कार्यक्रमहरू",
  "profile": "प्रोफाइल",
  "eventRequests": "कार्यक्रम अनुरोधहरू",
  "noPendingRequests": "कुनै विचाराधीन अनुरोधहरू छैनन्",
  "byOrganizer": "{organizer} द्वारा",
  "eventRejected": "कार्यक्रम अस्वीकृत गरियो",
  "reject": "अस्वीकार गर्नुहोस्",
  "eventApproved": "कार्यक्रम स्वीकृत गरियो",
  "approve": "स्वीकृत गर्नुहोस्",
  "noUserLoggedIn": "कुनै प्रयोगकर्ता लगइन भएको छैन",
  "administrator": "प्रशासक",
  "organisers": "आयोजकहरू",
  "attendees": "सहभागीहरू",
  "revenue": "राजस्व",
  "nprRevenue": "NPR {revenue}",
  "quickActions": "द्रुत कार्यहरू",
  "addOrganiser": "आयोजक\nथप्नुहोस्",
  "eventRequestsQuickAction": "कार्यक्रम\nअनुरोधहरू",
  "reports": "रिपोर्टहरू",
  "allEvents": "सबै कार्यक्रमहरू",
  "seeAll": "सबै हेर्नुहोस्",
  "auditoriumOccupancy": "सभागृहको उपस्थिति",
  "seatsBooked": "{booked} / {total} सिटहरू बुक गरियो",
  "myProfile": "मेरो प्रोफाइल",
  "editProfile": "प्रोफाइल सम्पादन गर्नुहोस्",
  "name": "नाम",
  "phone": "फोन",
  "cancel": "रद्द गर्नुहोस्",
  "pleaseFillAllFields": "कृपया सबै क्षेत्रहरू भर्नुहोस्",
  "profileUpdatedSuccessfully": "प्रोफाइल सफलतापूर्वक अद्यावधिक भयो",
  "save": "बचत गर्नुहोस्",
  "email": "इमेल",
  "resetPassword": "पासवर्ड रिसेट गर्नुहोस्",
  "newPassword": "नयाँ पासवर्ड",
  "passwordChangedSuccessfully": "पासवर्ड सफलतापूर्वक परिवर्तन भयो",
  "update": "अद्यावधिक गर्नुहोस्",
  "signOut": "साइन आउट गर्नुहोस्",
  "eventopiaAnalytics": "Eventopia विश्लेषण",
  "report": "रिपोर्ट",
  "eventDetails": "कार्यक्रमको विवरण",
  "nameDetail": "नाम: {name}",
  "dateDetail": "मिति: {date}",
  "organizerDetail": "आयोजक: {organizer}",
  "locationDetail": "स्थान: {location}",
  "kpi": "मुख्य प्रदर्शन सूचकहरू",
  "metric": "मेट्रिक",
  "value": "मान",
  "totalTicketsSold": "कुल टिकट बिक्री",
  "totalRevenue": "कुल राजस्व",
  "occupancyRate": "उपस्थिति दर",
  "availableSeats": "उपलब्ध सिटहरू",
  "salesByTicketCategory": "टिकट श्रेणी अनुसार बिक्री",
  "category": "श्रेणी",
  "ticketsSold": "टिकट बिक्री भयो",
  "generatedOnBySystem": "Eventopia प्रणाली द्वारा {date} मा उत्पन्न",
  "failedToGeneratePdf": "PDF उत्पन्न गर्न विफल: {error}",
  "reportsAndAnalytics": "रिपोर्ट र विश्लेषण",
  "noEventsToShowAnalytics": "विश्लेषण देखाउन कुनै कार्यक्रमहरू उपलब्ध छैनन्।",
  "selectEvent": "कार्यक्रम चयन गर्नुहोस्",
  "ofTotal": "{total} कुल मध्ये",
  "occupancy": "उपस्थिति",
  "available": "उपलब्ध",
  "sevenDayRevenue": "७-दिनको राजस्व",
  "salesByCategory": "श्रेणी अनुसार बिक्री",
  "passwordChangedPleaseLogin": "पासवर्ड सफलतापूर्वक परिवर्तन भयो। कृपया लगइन गर्नुहोस्।",
  "changePassword": "पासवर्ड परिवर्तन गर्नुहोस्",
  "enterNewPasswordDesc": "आफ्नो खाता सुरक्षित गर्न तल नयाँ पासवर्ड प्रविष्ट गर्नुहोस्।",
  "entryApprovedFor": "\"{title}\" को लागि प्रवेश स्वीकृत गरियो",
  "qrCodeNotFound": "QR कोड फेला परेन वा पहिले नै प्रयोग गरिसकिएको छ।",
  "qrCheckIn": "QR चेक-इन",
  "scanQrAtGate": "प्रवेश द्वारमा QR स्क्यान गर्नुहोस्",
  "manualQrCodeEntry": "म्यानुअल QR कोड प्रविष्टि",
  "enterQrCode": "QR कोड प्रविष्ट गर्नुहोस्",
  "validateEntry": "प्रवेश मान्य गर्नुहोस्",
  "noEventsAvailable": "कुनै कार्यक्रमहरू उपलब्ध छैनन्",
  "all": "सबै",
  "deleteUser": "प्रयोगकर्ता मेटाउनुहोस्",
  "areYouSureDeleteUser": "के तपाईं {name} लाई मेटाउन निश्चित हुनुहुन्छ?",
  "delete": "मेटाउनुहोस्",
  "editUser": "प्रयोगकर्ता सम्पादन गर्नुहोस्",
  "organisation": "संस्था",
  "manageEvent": "कार्यक्रम व्यवस्थापन गर्नुहोस्",
  "changeStatus": "स्थिति परिवर्तन गर्नुहोस्",
  "deleteEvent": "कार्यक्रम मेटाउनुहोस्",
  "areYouSureDeleteEvent": "के तपाईं यो कार्यक्रम मेटाउन निश्चित हुनुहुन्छ? यो कार्य फिर्ता लिन सकिँदैन।",
  "saveChanges": "परिवर्तनहरू बचत गर्नुहोस्",
  "scanAttendeeQr": "सहभागीको QR स्क्यान गर्नुहोस्",
  "cameraOpensHere": "क्यामेरा यहाँ खुल्छ",
  "mobileScannerPlugin": "(mobile_scanner प्लगइन)",
  "close": "बन्द गर्नुहोस्",
  "organiserRegistered": "आयोजक दर्ता भयो!",
  "organiserLoginCredentialsAssigned": "आयोजकलाई लगइन प्रमाणहरू तोकिएको छ। उनीहरूले पूर्वनिर्धारित पासवर्ड (Org@1234) प्रयोग गर्न सक्छन् र पहिलो लगइनमा परिवर्तन गर्न सक्छन्।",
  "done": "सम्पन्न भयो",
  "registerNewOrganiser": "नयाँ आयोजक दर्ता गर्नुहोस्",
  "defaultPasswordAssignedDesc": "एउटा पूर्वनिर्धारित पासवर्ड (Org@1234) तोकिनेछ र आयोजकलाई इमेल गरिनेछ। उनीहरूले यसलाई पहिलो लगइनमा परिवर्तन गर्नुपर्छ।",
  "required": "आवश्यक",
  "invalidEmail": "अमान्य इमेल",
  "organisationNameOptional": "संस्थाको नाम (वैकल्पिक)",
  "registerOrganiser": "आयोजक दर्ता गर्नुहोस्",
  "myEvents": "मेरा कार्यक्रमहरू",
  "analytics": "विश्लेषण",
  "organiser": "आयोजक",
  "nprParam": "NPR {param}",
  "promoCodes": "प्रोमो कोडहरू",
  "createAction": "+ सिर्जना गर्नुहोस्",
  "noEventsYet": "अहिलेसम्म कुनै कार्यक्रमहरू छैनन्।",
  "tapCreateToAddFirstEvent": "तपाईंको पहिलो कार्यक्रम थप्न \"+ सिर्जना गर्नुहोस्\" मा ट्याप गर्नुहोस्।",
  "create": "सिर्जना गर्नुहोस्",
  "eventAnalyticsReport": "कार्यक्रम विश्लेषण रिपोर्ट",
  "nameParam": "नाम: {param}",
  "dateParam": "मिति: {param}",
  "kpis": "मुख्य प्रदर्शन सूचकहरू (KPIs)",
  "generatedBySystem": "Eventopia प्रणाली द्वारा उत्पन्न",
  "createEventsToSeeAnalytics": "विश्लेषण हेर्न कार्यक्रमहरू सिर्जना गर्नुहोस्।",
  "downloadPdfReport": "PDF रिपोर्ट डाउनलोड गर्नुहोस्",
  "ofParamTotal": "{param} कुल मध्ये",
  "ticketVerified": "टिकट प्रमाणित भयो",
  "scanFailed": "स्क्यान विफल भयो",
  "ok": "ठिक छ",
  "scanTicket": "टिकट स्क्यान गर्नुहोस्",
  "requiredField": "आवश्यक",
  "eventAddedSuccessfully": "कार्यक्रम सफलतापूर्वक थपिएको छ!",
  "createNewEvent": "नयाँ कार्यक्रम सिर्जना गर्नुहोस्",
  "eventPoster": "कार्यक्रम पोस्टर",
  "change": "परिवर्तन गर्नुहोस्",
  "remove": "हटाउनुहोस्",
  "tapToAddEventPoster": "कार्यक्रम पोस्टर थप्न ट्याप गर्नुहोस्",
  "recommendedPosterSize": "सिफारिस गरिएको: १२०० × ८०० px",
  "eventTitle": "कार्यक्रमको शीर्षक",
  "description": "विवरण",
  "location": "स्थान",
  "date": "मिति",
  "start": "सुरु",
  "end": "अन्त्य",
  "ticketCategories": "टिकट श्रेणीहरू",
  "priceNpr": "मूल्य (NPR)",
  "capacity": "क्षमता",
  "promoCodeOptional": "प्रोमो कोड (वैकल्पिक)",
  "codeExample": "कोड (जस्तै SAVE20)",
  "discountPercentage": "छुट %",
  "createEvent": "कार्यक्रम सिर्जना गर्नुहोस्",
  "minParam": "न्यूनतम {param}",
  "editEvent": "कार्यक्रम सम्पादन गर्नुहोस्",
  "time": "समय",
  "seats": "सिटहरू",
  "ticketTypes": "टिकट प्रकारहरू",
  "paramOff": "{param}% छुट",
  "explore": "अन्वेषण गर्नुहोस्",
  "tickets": "टिकटहरू",
  "discoverConnectCelebrate": "अन्वेषण गर्नुहोस्। जोडिनुहोस्। उत्सव मनाउनुहोस्।",
  "myBookings": "मेरा बुकिङहरू",
  "totalSpent": "कुल खर्च",
  "nprAmount": "NPR {amount}",
  "upcomingEvents": "आगामी कार्यक्रमहरू",
  "noUpcomingEvents": "कुनै आगामी कार्यक्रमहरू छैनन्।",
  "bookings": "बुकिङहरू",
  "exploreEvents": "कार्यक्रमहरू अन्वेषण गर्नुहोस्",
  "searchEvents": "कार्यक्रमहरू खोज्नुहोस्…",
  "noEventsMatchSearch": "तपाईंको खोजीसँग कुनै कार्यक्रमहरू मेल खाँदैनन्।",
  "eventUpper": "कार्यक्रम",
  "completedUpper": "सम्पन्न",
  "upcomingUpper": "आगामी",
  "about": "बारेमा",
  "availablePromoCodes": "उपलब्ध प्रोमो कोडहरू",
  "useCodeForDiscount": "{discount}% छुटको लागि कोड {code} प्रयोग गर्नुहोस्!",
  "remainingCount": "{count} बाँकी",
  "eventEnded": "कार्यक्रम समाप्त भयो",
  "bookNow": "अहिले बुक गर्नुहोस्",
  "notAvailable": "उपलब्ध छैन",
  "myTickets": "मेरा टिकटहरू",
  "upcoming": "आगामी",
  "past": "विगत",
  "cancelled": "रद्द गरियो",
  "noTicketsYet": "अहिलेसम्म कुनै टिकटहरू छैनन्।",
  "notifications": "सूचनाहरू",
  "noNotificationsYet": "अहिलेसम्म कुनै सूचनाहरू छैनन्",
  "payment": "भुक्तानी",
  "otpSentMessage": "तपाईंको दर्ता गरिएको मोबाइल/इमेलमा OTP पठाइएको छ। (पूर्वनिर्धारित: १२३४)",
  "invalidOtpMessage": "अमान्य OTP। कृपया पुन: प्रयास गर्नुहोस्।",
  "orderSummary": "अर्डर सारांश",
  "event": "कार्यक्रम",
  "ticket": "टिकट",
  "categoryQuantity": "{category} × {quantity}",
  "subtotal": "उप-कुल",
  "promoCode": "प्रोमो: {code}",
  "negativeNprAmount": "- NPR {amount}",
  "totalToPay": "तिर्नुपर्ने कुल रकम",
  "selectPaymentMethod": "भुक्तानी विधि चयन गर्नुहोस्",
  "card": "कार्ड",
  "esewa": "ईसेवा",
  "pay": "तिर्नुहोस्",
  "enterOtpToConfirm": "भुक्तानी पुष्टि गर्न OTP प्रविष्ट गर्नुहोस्",
  "otpLabel": "OTP : १२३४",
  "verifyAndPay": "प्रमाणित गर्नुहोस् र तिर्नुहोस् – NPR {amount}",
  "maxSeatsAllowed": "प्रति बुकिङ अधिकतम १० सिटहरू अनुमति छ।",
  "chooseTicketCategoryFirst": "पहिले टिकट श्रेणी छनौट गर्नुहोस्",
  "categoryPrice": "{category} (NPR {price})",
  "selected": "चयन गरियो",
  "booked": "बुक गरियो",
  "pleaseSelectCategory": "सिटहरू छनौट गर्न कृपया टिकट श्रेणी चयन गर्नुहोस्",
  "stageUpper": "मञ्च",
  "controlRoomUpper": "नियन्त्रण कक्ष",
  "seatsSelected": "{count} सिट(हरू) चयन गरियो",
  "continueAction": "अगाडि बढ्नुहोस्",
  "eventopiaUpper": "EVENTOPIA",
  "eTicketUpper": "ई-टिकट",
  "confirmedUpper": "पुष्टि भयो",
  "detail": "विवरण",
  "info": "जानकारी",
  "ticketType": "टिकट प्रकार",
  "quantity": "मात्रा",
  "section": "खण्ड",
  "discount": "छुट",
  "totalPaid": "कुल भुक्तान",
  "bookedOn": "बुक गरिएको मिति",
  "reference": "सन्दर्भ",
  "scanQrAtEntry": "प्रवेश द्वारमा यो QR स्क्यान गर्नुहोस्",
  "generatedBy": "{date} मा Eventopia द्वारा उत्पन्न",
  "ticketConfirmed": "टिकट पुष्टि भयो!",
  "showQrAtEntry": "प्रवेश द्वारमा यो QR कोड देखाउनुहोस्",
  "promoApplied": "कोड लागू भयो! {discount}% छुट",
  "invalidPromoCode": "अमान्य वा म्याद सकिएको कोड",
  "bookingFailed": "बुकिङ विफल भयो। कृपया पुन: प्रयास गर्नुहोस्।",
  "selectTicketType": "टिकट प्रकार चयन गर्नुहोस्",
  "countLeft": "{count} बाँकी",
  "apply": "लागू गर्नुहोस्",
  "discountWithPercent": "छुट ({discount}%)",
  "total": "कुल",
  "selectATicketType": "एउटा टिकट प्रकार चयन गर्नुहोस्",
  "proceedToPay": "भुक्तानी गर्न अगाडि बढ्नुहोस्",
  "eventSoldOut": "यो कार्यक्रम बिक्री भइसकेको छ।",
  "onWaitlist": "तपाईं प्रतीक्षा सूचीमा हुनुहुन्छ!",
  "joinWaitlistDesc": "प्रतीक्षा सूचीमा सामेल हुनुहोस् — टिकटहरू उपलब्ध भएपछि हामी तपाईंलाई सूचित गर्नेछौं।",
  "joinWaitlist": "प्रतीक्षा सूचीमा सामेल हुनुहोस्",
  "quantityMultiplier": "× {quantity}",
  "downloadTicket": "टिकट डाउनलोड गर्नुहोस्",
  "bookingCancelledRefunded": "यो बुकिङ रद्द गरिएको छ। फिर्ता रकम प्रदान गरिएको छ।",
  "bookingCancelledRefundedSuccess": "बुकिङ रद्द गरियो। फिर्ता रकम प्रदान गरिएको छ।",
  "cannotCancelWindowPassed": "रद्द गर्न सकिँदैन — ७-दिनको समय सीमा समाप्त भयो।",
  "cancelBooking": "बुकिङ रद्द गर्नुहोस्"
}

def extract_params(value):
    return re.findall(r'\{(\w+)\}', value)

en_arb = {"@@locale": "en"}
for k, v in en_dict.items():
    en_arb[k] = v
    params = extract_params(v)
    if params:
        placeholders = {}
        for p in params:
            placeholders[p] = {"type": "String", "example": p}
        en_arb[f"@{k}"] = {
            "description": f"Text for {k}",
            "placeholders": placeholders
        }
    else:
        en_arb[f"@{k}"] = {
            "description": f"Text for {k}"
        }

ne_arb = {"@@locale": "ne"}
for k, v in ne_dict.items():
    ne_arb[k] = v

os.makedirs(r"c:\Users\Anjeesha\StudioProjects\Eventopia\lib\l10n", exist_ok=True)

with open(r"c:\Users\Anjeesha\StudioProjects\Eventopia\lib\l10n\app_en.arb", "w", encoding="utf-8") as f:
    json.dump(en_arb, f, indent=2, ensure_ascii=False)
    
with open(r"c:\Users\Anjeesha\StudioProjects\Eventopia\lib\l10n\app_ne.arb", "w", encoding="utf-8") as f:
    json.dump(ne_arb, f, indent=2, ensure_ascii=False)

print("ARB files generated successfully.")
